### PR TITLE
docs: README note on usage

### PR DESCRIPTION
**Pull request by Neo23x0**

### CODE REVIEW

**Review by m3636 — APPROVED** [review]

**Comment by NUL0x4C** [comment]
@Neo23x0 bro idk what do u want, please write your yara rule thing and stop acting funny

**Comment by Neo23x0** [comment]
I just wanted to help. You should add that notice so that no one uses that code for criminal purposes but only for legitimate software that deletes the volume shadow copies on a system.

**Comment by NUL0x4C** [comment]
pov: blue teamer karen on a github pr

**Comment by Neo23x0** [comment]
😄 not only github! I also shared my opinion on your great piece of work on Twitter.

**Comment by NUL0x4C** [comment]
good for you

**Comment by 420SmokeBigWeedHackBadDrivers** [comment]
> 😄 not only github! I also shared my opinion on your great piece of work on Twitter.

Cope harder Florian.

**Pull request closed without merging**
